name: issue_response

on:
  issues:
    types:
      - opened

jobs:
  comment:
    runs-on: windows-latest

    steps:
      - name: Set up Git
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Create comment
        run: |
          $commentBody = @{
            body = "ğŸ‰ Thank You for Raising This Issue! ğŸ‰`n`n![Meme](https://example.com/meme.jpg)`n`nPlease wait patiently while we look into it. ğŸ•’`n`nWe appreciate your contribution! Feel free to grab a â˜•ï¸ or enjoy some ğŸ• while we work on a solution.`n`nHave a great day! ğŸ˜„"
          }
          Invoke-RestMethod -Uri "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments" -Headers @{
            "Authorization" = "Bearer $env:GITHUB_TOKEN"
            "Content-Type" = "application/json"
          } -Method Post -Body ($commentBody | ConvertTo-Json)
