name: Windows Action Example with Fun

on:
  issues:
    types:
      - opened

jobs:
  comment:
    runs-on: windows-latest

    steps:
      - name: Set up Git
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Create comment
        run: |
          echo "ğŸ‰ Thank You for Raising This Issue! ğŸ‰"
          echo ""
          echo "![Meme](https://static.pupperish.com/images/iuhNwqKdFMPn_3895_700.jpg)"
          echo ""
          echo "Please wait patiently while we look into it. ğŸ•’"
          echo ""
          echo "We appreciate your contribution! Feel free to grab a â˜•ï¸ or enjoy some ğŸ• while we work on a solution."
          echo ""
          echo "Have a great day! ğŸ˜„"
